// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg1XgCpMEEkczLITnT0ILmroGZydVafoA',
    appId: '1:274581856496:web:911dd71a27a9d7096ee235',
    messagingSenderId: '274581856496',
    projectId: 'smart-agriculture-system-c8361',
    authDomain: 'smart-agriculture-system-c8361.firebaseapp.com',
    databaseURL: 'https://smart-agriculture-system-c8361-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-agriculture-system-c8361.firebasestorage.app',
    measurementId: 'G-ZNJL6H6PZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEGAZRODaCA_DcnXQyFuq4PotKLu4ELM8',
    appId: '1:274581856496:android:13a3bba30bbd7b526ee235',
    messagingSenderId: '274581856496',
    projectId: 'smart-agriculture-system-c8361',
    databaseURL: 'https://smart-agriculture-system-c8361-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-agriculture-system-c8361.firebasestorage.app',
  );
}
